### ISSUE TITLE
yml file sets IntaRNA 2.1.0

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA-benchmark-SHAPE#1]
https://github.com/BackofenLab/IntARNA-SHAPE/blob/422c084610f080d6ae921cae12172c268efb117d/conda-env-IntaRNA-SHAPE.yml#L11

shouldnt it be 2.2.0 ?

**Comment by mmiladi** [comment]
The yml has not been updated a while. Testing conda intarna started..

**Comment by mmiladi** [comment]
Should have been fixed by: 
https://github.com/BackofenLab/IntaRNA-benchmark-SHAPE/commit/a1c59a1b8b02507811301f7ac0bd68b0835d1df3

**Comment by martin-raden** [comment]
*thumbsup*
